apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tempssd-apps
  labels:
    lauckserv.io/environment: tempssd
    lauckserv.io/category: app-set
spec:
  generators:
    - git:
        repoURL: https://github.com/lauckserv/ops-cluster-dev
        revision: HEAD
        directories:
          - path: apps/**/*
  template:
    metadata:
      name: "tempssd-{{path.basename}}"
      labels:
        lauckserv.io/environment: tempssd
        lauckserv.io/category: app
    spec:
      project: "{{ path[1] }}-apps"
      source:
        repoURL: https://github.com/lauckserv/ops-cluster-dev
        path: "{{ path }}"
        targetRevision: main
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://192.168.225.13:6443
        namespace: "{{ path[2] }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true